name = "githubactions4julia"
uuid = "bb6569f5-f955-44f5-a34b-96740b440080"
authors = ["wakakusa"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
